name: MinecraftGroupmeChatPlugin
version: 1.0.0
author: Chris Dalke
main: com.chrisdalke.minechat.MinecraftGroupmeChatPlugin
commands:
  minechat:
    description: Enables or disables Minecraft-Groupme Chat.
    usage: /minechat <enable/disable>